package org.main;

class Brackets{
	
//	private Object lock="lock";
	private static String lockCode;
	
	
	
//	public Brackets(String lockCode) {
//		this.lockCode = lockCode;
//	}



	synchronized public static void generate(String lockCode) {
//		synchronized (lock) {
		for(int i=0; i<=10; i++) {
			
			try {
				Thread.sleep(10);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			if(i<=5) {
				System.out.print("[");
			} else {
				System.out.print("]");
			}
			
		}
		System.out.println("Generated by thread "+lockCode);
//		}
		
		
//		for (int j=0; j<=10; j++) {
//			try {
//				Thread.sleep(25);
//			} catch (InterruptedException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//		}
	}
}

public class Async {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
//		Brackets newBracket = new Brackets("Thread 1");
//		Brackets newBracket2 = new Brackets("Thread 2");
//		newBracket.generate();
		
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				// TODO Auto-generated method stub
				for(int i =0; i<=5; i++) {
					Brackets.generate("String 1");
				}
				
			}
		}).start();
		
		new Thread(new Runnable() {
					
					@Override
					public void run() {
						// TODO Auto-generated method stub
						for(int i =0; i<=5; i++) {
							Brackets.generate("String 2");
						}
						
					}
				}).start();
		}

}
